services:
  mysql:
    image: mysql:8.0
    container_name: apartment_sales_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 123barac123
      MYSQL_DATABASE: apartment_sales
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/config/init_apartments.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p123barac123"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:
